### ISSUE TITLE
Fix `Protection Mode` connections to mode switcher

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/gpc-optmeowt#216]
The overall framework for OptMeowt's mode switcher has been completed in #204. This is about 90% of what I intended to accomplish there, though there are still a few quirks with rewiring the protection-mode that need to be worked out. Let's use this issue to tackle that remaining 10%. 

I'll make sure to add any other minor bugs I find to this top comment.

### To-Do

- [x] Make sure storageCookies.js works exclusively with protection-mode (i.e. double check storage.js)
- [x] Plug in `enable` functions for protection-mode, i.e., `protection.preinit()`, `protection.init()`, etc. 
- [x] If building for analysis-mode, make sure imports don't cause the protection-mode cookies to install (or any other functions we don't want)

**Comment by kalicki1** [comment]
This looks to be all set! I'll go ahead and close this issue.
