### ISSUE TITLE
Validate analysis functionality

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#242]
@kalicki1 will write in more detail here during testing with the validation set what the problems are with the different sites, if any, ideas how to address those, and so on.

We first need to update the groundtruth in the validation set. Some sites may have the US Privacy String now, and they did not have it before, for example. Then, we would need to run OptMeowt with a regular IP address and a California IP address, and compare the results of OptMeowt against the groundtruth, and fix, as necessary.

**Comment by SebastianZimmeck** [comment]
I am making this an omnibus issue for all the small points we detect and need to fix during validation testing. @kalicki1 and @OliverWang13, please feel free to open individual issues if you feel that is better.

- [ ] As @kalicki1 [described](https://github.com/privacy-tech-lab/gpc-optmeowt/issues/238#issuecomment-977709684), there is an issue with guardian.com: "That leaves theguardian.com as the only site I don't have an explanation for. To me it feels like it might be an infinite-scroll style issue, ... ."  What might be the problem, and how can we fix it? If it is a one-off issue, we may be also able to tolerate it.
- [ ] As @kalicki1 also [described](https://github.com/privacy-tech-lab/gpc-optmeowt/issues/238#issuecomment-977709684), there is an issue with disqus.com. Here we discussed today, is it possible to fix the problem by using @OliverWang13's Do Not Sell link identification method?
- [ ] As @kalicki1 also [described](https://github.com/privacy-tech-lab/gpc-optmeowt/issues/238#issuecomment-977709684), there were some sites that use the USPAPI but return a US Privacy String of `1---`. It seems OK to me to not flag this. However, we should test whether there is a change in the String when using a Californian IP address.
- [ ] There were some sites where the Do Not Sell link identification failed because they had something like "California ... Do Not Sell" as link language. Can we identify this type of link language by changing the regex, e.g., also taking into consideration tags like `<a>` or maybe do a one-off solution changing the regex such that it captures the particular case. The issue is to avoid general "do not sell on eBay" and similar language that would create false positives.

**Comment by kalicki1** [comment]
@SebastianZimmeck I checked off your first point since it overlaps with your last bullet point (the "California ... Do Not Sell" language site is actually theguardian.com).

I took a look at the source of the specific JS file that renders the Do Not Sell link on theguardian.com (relating to the last bullet point) to try and see if we can easily search for `<a>` tags there. On first glance it seems that picking up on `<a>` tag insertions in obfuscated JS code might be trickier than we think. Feel free to take a look at a snippet of the code with the "California resident ... Do Not Sell" language (with extra code for context). 

>{showMeTheEpic:qe,showMeTheBanner:Ve,showMeTheDoubleBanner:Fe,showNextVariant:Ge,showPreviousVariant:$e,changeGeolocation:We}},Ke=n(35),Ye=n(34),Qe=function(){if(h.a.get("switches.consentManagement",!0)){var e=document.querySelector("a[data-link-name=privacy]");if(e){var t=e.parentElement;if(t){var n=e.cloneNode(!1);n.dataset.linkName="privacy-settings",n.removeAttribute("href"),n.innerText=function(){if(void 0===r){var e=Object(Ye.e)();r={ccpa:e,tcfv2:!e}}return r}().ccpa?"**California resident â€“ Do Not Sell**":"Privacy settings";var a=t.cloneNode(!1);a.appendChild(n),t.insertAdjacentElement("beforebegin",a),n.addEventListener("click",(function(){Ke.a.showPrivacyManager()}))}}}}


On another point: 

I feel that changing the regular expression to catch "Do Not Sell" is not the best idea either if we can't catch link elements with Do Not Sell language reliably. I have already found false positives in my limited trial with the new pattern.

**Comment by SebastianZimmeck** [comment]
I agree with your assessment, @kalicki1. Just "Do Not Sell" should be not sufficient for declaring a positive Do Not Sell link find. If you or @OliverWang13 do not have a better idea, my suggestion is to change the regex so that it narrowly captures the case at hand `"California resident â€“ Do Not Sell"`. The Euro and other weird character seems like there was another character that could not be shown with the available character set. So, I would disregard that and allow for one or more random characters between "California resident" and "Do Not Sell". Not a great solution, but OK.

**Comment by kalicki1** [comment]
I updated the regular expression to include the following, alongside the old pattern:
`/((California|CA).?Resident).{0,10}((Do.?Not|Don.?t).?Sell)/gmi`

This should catch patterns such as `California Resident -- Do Not Sell` or `CA Resident -- Do Not Sell`; I gave it a little leeway so that it could potentially catch other sites with similar language. I did however cap the space in between the "California Resident" and "Do Not Sell" language at 10 characters.

**Comment by kalicki1** [comment]
### "Do Not Sell" Regex edge case
I tested the new regular expression on `theguardian.com` and luckily it does catch the Do Not Sell string as the page is loaded. 🥳 However, now the link is caught and stored under a different domain from `theguardian.com` as it is loaded by a custom content delivery location, specifically `guim.co.uk`. As a result, our current solution doesn't register `theguardian.com` as DNS compliant. Here's a screenshot from the analysis data:

![Screen Shot 2021-11-29 at 4 31 49 PM](https://user-images.githubusercontent.com/60238705/143946094-4c4ea5f1-58c7-40bc-9e85-95b62ebc6beb.png)

Luckily this new problem is the same problem that we have with `disqus.com` (its DNS link is loaded by `disquscdn.com`). If we are able to find a solution for this problem, we should be able to close out this issue. 

### Ideas on this "DNS link saved on a different domain" issue
An idea I had that might work was to associate any requests, regardless of what domain makes them, with the domain of the URL of the site we are visiting, and to load all of them into the 1st party's entry. This could be possible now that I made a recent switch to initiate and halt our analysis mode manually, which would prevent associating incorrect requests across site navigations. 

My only concern is that by doing something like this we could create more false positives than we would like. @SebastianZimmeck @OliverWang13 let me know if either of you have any thoughts on this particular issue.

**Comment by SebastianZimmeck** [comment]
> My only concern is that by doing something like this we could create more false positives than we would like.

I think that is a good idea!

Especially, given that we found this pattern already in disqus.com and theguardian.com, it is likely that it will exist elsewhere as well.

What would be a scenario where we introduce false positives? At least, currently with the manual starting and stopping of the analysis wouldn't it be pretty clear what the current first party site is?

**Comment by kalicki1** [comment]
> At least, currently with the manual starting and stopping of the analysis wouldn't it be pretty clear what the current first party site is?

@SebastianZimmeck I think you are right. At the time I was worried about third parties having their own DNS links in resource JS files that don't appear on the page or similarly USP strings that aren't used by the first party, but on second thought I don't think that will be an issue.

I'll go ahead and implement this; then we can run our analysis on the validation set to be sure. I believe this will be the last step prior to validating everything for the last time.

**Comment by kalicki1** [comment]
### Associating requests with the 1st party domain

As discussed, I pushed a change that associates our all requests made while running an `Analysis Mode` test with the current page's first party domain. I ran a very small test on `theguardian.com` and `disqus.com` and found that our problem is essentially resolved. Below is a screenshot of the results. Note that only the first parties appear, and the DNS links return true for both sites when they previously did not. 

<img width="550" alt="Screen Shot 2021-12-01 at 9 02 42 PM" src="https://user-images.githubusercontent.com/60238705/144344540-26f4ccb5-3f3a-4aaa-9cb6-145294a8235a.png">

### A small side observation

I was watching the cookies while on `theguardian.com` and saw a USP string of the form `1NYN` appear a few times, on both `theguardian.com` and `google.com` at different times. I cleared my cookies and reran the test a few times but could not figure out why this was the case. In all my trials, the actual `__USPAPI()` call returned `1NNN`.

**Comment by kalicki1** [comment]
> there were some sites that use the USPAPI but return a US Privacy String of 1---. It seems OK to me to not flag this.

@SebastianZimmeck, in your comment from Nov 24th did you mean to continue to mark `1---` strings as "compliant" in the sense that we "check off" our fourth analysis box in the popup, i.e. `US Privacy String Updated`? For the sake of our analysis I'm not sure this matters all that much since we do save the actual USP string. As a UI question however, this is somewhat related to our Compliance element issue (#244).

If you meant we should keep it as is, then we can close this out. Otherwise, I'll push a small change to fix this and have it mark as false.

**Comment by kalicki1** [comment]
I went ahead and manually updated our Validation set in our Google doc with what I could find on each webpage. From here, we should be ready to run another test (hopefully the last 🤞🏻) to double check OptMeowt's results match one-to-one with the set I just put together.

**Comment by SebastianZimmeck** [comment]
> Otherwise, I'll push a small change to fix this and have it mark as false.

Yes, for the time being, let's have a little red x.

We generally have the problem that we have situations where we have at least one x but the site is still compliant. For example, if they honor GPC only in California and, thus, do not update the US Privacy String. Let's discuss this later today ...

**Comment by SebastianZimmeck** [comment]
As we discussed in our call, we go with the x because we are assuming that users are in California, in which case a string with `1___` would be not compliant. And maybe, we actually add the string to the UI (popup and settings).

**Comment by SebastianZimmeck** [comment]
In addition, @kalicki1 will also add to the analysis settings page something like "If you are not in California, websites may not honor your CCPA request."

**Comment by kalicki1** [comment]
@OliverWang13, I'm working on changing the UI to show an X instead of a check when we have a `1---`, however in order to do this I'm changing our backend implementation. 

Instead of saving `USPAPI_OPTED_OUT` as "N/A - Outside CA" (what matters is this is a non-empty string), I will save it as a false boolean. This will allow us to keep your frontend the same, though we will no longer be able to visually scan the `USPAPI_OPTED_OUT` column in our downloaded CSV to find sites which say we are not in CA. We will instead have to find false cases and double check the saved string is `1---`. This may or may not affect what you are doing.

**Comment by kalicki1** [comment]
I ended up deciding to change how I discussed implementing the above change.

 Instead of changing `USPAPI_OPTED_OUT` to a boolean in the outside-CA case, I went ahead and kept it a string and updated the frontend to check for strings to parse before checking for boolean values. I ran into some trouble with my previous approach regarding cases that fail to parse the string at all, such as the `null` returned value from `huffpost.com`. In order to cover this case and the outside-CA case, I decided to use two strings that we explicitly check for in the frontend: 
- `PARSE_FAILED`
- `NOT_IN_CA`

If either of these are recognized, the frontend renders their corresponding `USPAPI_OPTED_OUT` element as an X.

**Comment by OliverWang13** [comment]
Nice, @kalicki1 that all sounds good.

**Comment by OliverWang13** [comment]
I was working through the validation set and came across `foxnews.com` which had a 1--- string. With the VPN working, it should not have displayed that. Further work will be done to figure out if this is a problem on our end or their end.

**Comment by kalicki1** [comment]
### US Privacy strings
After taking a look at some of the inconsistencies in detecting USP Strings across certain sites, I decided to try out switching our USPAPI call from immediately after the main page we are visiting loads to right before we run and stop the analysis itself with a blocking call. This ended up resolving all of the does-not-exist issues with any sites that do have the USPAPI, especially for one problematic site that seemed to always load the endpoint a few seconds after the main page loaded. This is easily extensible to add in cookies if we wish, as we are currently not checking for them at all in OptMeowt. 

This leaves two bigger concerns however: 
1. Do we want to give websites the grace to load the USPAPI at any point in time? I'm not the biggest fan of this simply because a lot of transactions happen right as the page loads, but it gives us the most consistent results and resolves all of our USPAPI issues.
2. There is only one site that currently does not have the USPAPI implemented in our validation set. In other words, we miss only one site because it only uses a us_privacy cookie. Should we add cookie functionality back in to catch this edge case? 

Smaller concerns:
1. buzzfeed.com and HuffPost.com still do not actually return a value from their USPAPI. Currently OptMeowt treats this as non-compliance

### Do not sell links
Through checking our missed sites one by one (I still need to do one more pass through our validation set with the new OptMeowt commits), I only found one exception to our DNS system. theatlantic.com for some reason never registers with OptMeowt as having a do not sell link, even though when I scroll down (sometimes through a few extra page content loads) it ends up being in the footer. How hard do we want to press this edge case?

**Comment by kalicki1** [comment]
I have also done a little bit of poking around the us_privacy cookies since my new USPAPI call implementation hits every site and gives us results, except for the one site, dailymotion.com, that just doesn't have it implemented. 

It turns out that what we said last week about Condé Nast is right in that every magazine owned by Condé Nast automatically places a `1YYN` cookie, e.g. GQ, Architectural Digest, Wired, etc. Also, dailymotion.com, the site without the USPAPI, does not change the associated cookie (`1YNY`) with a GPC signal either way.

**Comment by kalicki1** [comment]
I'll go ahead and close this issue since we have finalized our Validation Set.
