### ISSUE TITLE
Switch to mv3 - part 2

### ISSUE THREAD

**Issue by SebastianZimmeck** [privacy-tech-lab/gpc-optmeowt#286]
This omnibus issue is a continuation of #175 as the switch to mv3 is not finished yet. This issue organizes our approach and the open issues to resolve. 

Going forward, @OliverWang13 will be our product manager keeping us organized and on track timewise with assistance by @kalicki1.

### 0. Current Status 

The #175 mv3 branch is merged into main. But there are at least three open questions:
1. When can we close out the **various open mv3 issues**?
2. How do we address the **switch to mv3 for Firefox**?
3. How can we start the **usability study** while we are in the process of switching to mv3?

In detail:

### 1. Various Open mv3 Issues

Here are the various mv3 issues and the order in which they need to be addressed:

- [x] #259 is the main problem; we have a timing problem for attaching the GPC signal via the DOM
- [x] #262 covers various clean-up work for the domain list that does not seem too problematic
- [ ] #283 once all functional mv3 changes have been made
- [ ] #213 pretty quick update of documentation
- [ ] #273 release of the final mv3 product

### 2. Switch to mv3 for Firefox

It seems to me we have largely worked on switching to mv3 from the Chrome perspective. It seems to me that the various open issues cover Chrome. It is far less clear what we do about Firefox. In fact, it seems that Firefox's own timeline for switching to mv3 is not clear at this point. Here is their most recent [blog post](https://blog.mozilla.org/addons/2022/05/18/manifest-v3-in-firefox-recap-next-steps/) on the topic. Two highlights:

>  Mozilla will maintain support for blocking WebRequest in MV3. To maximize compatibility with other browsers, we will also ship support for declarativeNetRequest.

So, we can leave our Firefox version as is?

> We’ve found Service Workers can’t fully support various use cases we consider important, especially around DOM-related features and APIs. ... In Firefox, we have decided to support Event Pages in MV3, and our developer preview will not include Service Workers (we’re continuing to work on supporting these for a future release).

On the long run, our Chrome and Firefox releases should be as similar as possible to keep the workload as small as possible. It  seems difficult to tell how our Firefox release will look like in the end given the current uncertainty of Firefox's concrete mv3 switch. Or can we? On the short run, do we keep the Firefox release essentially as is and switch to mv3 for Chrome only? Do we role back our mv3 release of Chrome? (see Usability study question below) Something else ...?

So what do we do?

### 3. How to Usability Study in the Midst of mv3 Switch?

The problem is that we are halfway in the switch (see #175) but also fairly far off from finalizing it. This is partly due to hitting difficult problems, especially, #259, partly because the final situation for Firefox is not known, and partly because our pace is too leisurely.

The big question is, can we push this through fairly quickly to move on to our research questions or do we need to roll back to mv2 and tackle mv3 again later? Or something in between, e.g., mv3 for Chrome and leave Firefox as is.

@OliverWang13 will take it from here and with @kalicki1's help organize and implement the switch to mv3.

**Comment by SebastianZimmeck** [comment]
Excellent! 

> This is not something I am extremely familiar with yet so I do not know how long this would take. 

I'd say, take two days, @OliverWang13, and try to gauge then how long this would take. Then, we can revisit.

**Comment by OliverWang13** [comment]
This has been completed.
